variable "azurerm_resource_group_name" {}
variable "azurerm_resource_group_location" {}
variable "azurerm_subnet_gateway" {}
variable "azurerm_subnet_management" {}
variable "azurerm_subnet_web" {}
variable "azurerm_subnet_logic" {}
variable "azurerm_subnet_data" {}
variable "ubuntu_version" {}
variable "azurerm_network_interface_web1" {}
variable "azurerm_network_interface_web2" {}
variable "azurerm_network_interface_logic1" {}
variable "azurerm_network_interface_logic2" {}
variable "azurerm_network_interface_data1" {}
